config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about'   => 'welcome#about'
  get 'signup' => 'users#new'
  get 'todo' => 'lists#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'users/:id/lists' => 'users#lists', :as => :user_lists
  get '/lists' => 'lists#index', :as => :lists
  post '/lists/new' => 'lists#create', :as => :new_list
  post '/lists/:id/todos/:id' => 'todo#changeDone', :as => :changeDone

  resources :users
  resources :lists do
    resources :todos
  end


end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :todos, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true,length: {minimum: 2, maximum:120}

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list
  validates :body, presence: true, length: {minimum:2}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :lists, dependent: :destroy

	attr_accessor :remember_token
	before_save { self.email = email.downcase }
  	validates :name,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password

    validates :username, presence:true, length: {maximum:12}, uniqueness: {case_sensitive: false}

    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # returns random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
  	update_attribute(:remember_digest, nil)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index

  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      #success
      redirect_to @list
    else
      render 'new'
    end
  end

  def destroy

    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path

  end

  private
  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or root_path
    else
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @todo = @list.todos.create(todo_params)
    redirect_to list_path(@list)

  end
  def new

  end

  def update
    @list = List.find(params[:list_id])
    @todo = @list.todos.find(params[:id])
    if @todo.update_attribute(:done, true)
      redirect_to list_path(@list), :notice => "You did it!"
    else
      render 'new'
    end

  end

  def destroy
    @list = List.find(params[:list_id])
    @todo = @list.todos.find(params[:id])
    @todo.destroy
    redirect_to list_path(@list)

  end


  private
  def todo_params
    params.require(:todo).permit(:body, :done)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      #notify user
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def lists
    if (params[:id])
      @user = User.find(params[:id])
    else
      @user = current_user
    end

    @lists = List.where(:user_id => @user.id)

  end

  private
  def user_params
  	params.require(:user).permit(:name,:username,:email,:password)
  end

  def logged_in_user
    unless logged_in?
      store_location
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user?(@user)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    if logged_in?
      redirect_to :controller => 'lists', :action => 'index'
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#log in user
	def log_in(user)
		session[:user_id] = user.id 
	end

	def remember(user)
    	user.remember
    	cookies.permanent.signed[:user_id] = user.id
    	cookies.permanent[:remember_token] = user.remember_token
  end
  def current_user?(user)
    user == current_user
  end

	#returns current user
	def current_user
		if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
    	raise
      	user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget(user)
  	user.forget
  	cookies.delete(:user_id)
  	cookies.delete(:remember_token)
  end
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end


	#return true if user is logged in
	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
   <p align="right">
     <small>
       <%= link_to "About", about_path %> -
       Simply Do © 2015 <a href="http://wwww.upalela.com">Upalela</a>
     </small>
    </p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <%= link_to "Simply Do", root_path, id: "logo" %>
        <nav>
           <ul class="nav navbar-nav">
			      <% if logged_in? %>
	            	<li><%= link_to "Lists", lists_path %></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                <li><%= link_to "+", new_list_path %></li>
        		<% else %>
              <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
      	  </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Simply Do.</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All your lists.</h1>
<table class="table table-striped">
  <tr><strong><h3>List name:</h3></strong></tr>
    <% current_user.lists.each do |l| %>
      <tr>
        <td class="single"><%= link_to list_path(l) do %><%= l.name %><% end %></td>
        <td align="right" class="single">
          <%= link_to list_path(l) do %><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><% end %>

          <%= link_to list_path(l), method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove" aria-hidden="true"></span><% end %>
        </td>
      </tr>
  <% end %>
</table>
<br>
<%= link_to "+ Create new list", new_list_path %>

app/views/lists/new.html.erb
<h3>Create a new list:</h3>
<br>
<div class="col-md-2">
  <%= form_for :list do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, :maxlength => 55, :required => true %>
        <%= f.submit "Create", class: "btn btn-default" %>
      </p>
  <% end %>
</div>

app/views/lists/show.html.erb
<br>
<table class="table table-striped" style="width:50%">
  <tr><strong><h3><%= @list.name %>:</h3></strong></tr>
    <% @list.todos.each do |todo| %>
      <% if todo.done == false %>
          <tr>
            <td class="single"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> <%= todo.body %></td>
            <td align="right" class="single">
              <%= link_to [todo.list, todo], method: :put do %>
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span><%end%>
              <%= link_to [todo.list, todo], method: :delete,data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span><%end%></td>
          </tr>
      <% end %>
    <% end %>
</table>
<br>

<p>Add a new todo:</p>
<div class="row">
  <div class="col-md-2">
    <%= form_for([@list, @list.todos.build], :html => {:class => "form-inline"}) do |f| %>
      <div class="form-group">
        <div class="input-group">
          <%= f.text_area :body, :required => true, :maxlength => 60 %>
          <%= f.submit "Submit", class: "btn btn-default" %>
        </div>
      </div>
    <%end%>
	</div>
</div>

<br><br>

<table class="table table-striped" style="width:50%">
  <tr><strong>DONE:</strong></tr>
    <% @list.todos.each do |todo| %>
      <% if todo.done == true %>
          <tr>
            <td class="single"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> <%= todo.body %></td>
      <% end %>
      </tr>
    <% end %>
</table>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissible">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="center jumbotron">
  <h1>Welcome to <i>Simply Do.</i></h1>
  <br>
	<h3>New to <i>Simply Do</i>? Then do sign up.</h3>
	<br>
	<div class="row">
	  <div class="col-md-4 col-md-offset-4">
				<%= form_for(@user) do |f| %>

					<%= render 'shared/error_messages' %>
					<%= f.label "Name:" %>
					<%= f.text_field :name,  placeholder:"Full Name", class: 'form-control'  %>

					<%= f.label "username:" %>
					<%= f.text_field :username, placeholder:"username",class: 'form-control'  %>

					<%= f.label "email:" %>
					<%= f.email_field :email, placeholder:"email@domain.com" , class: 'form-control'%>

					<%= f.label "password:" %>
					<%= f.password_field :password,  placeholder:"password", class: 'form-control'  %>

					<%= f.submit "Submit", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
	<br><br>
	<p>
		<%= link_to "Log in", root_path %>
	</p>
</div>

app/views/users/show.html.erb
<div class="center jumbotron">
	<h3>User</h3>
	<h4>Name: <b><%= @user.name %><br></b></h4>
	<h5>Username: <b><%= @user.username %></b></h5><br>
</div>

app/views/welcome/about.html.erb
<h1>About <i>simply do</i></h1>
<p>A simple web based to-do in Ruby on Rails.
<br>
Made by <a href="https://bitbucket.org/lilicosic">Lili Cosic</a> as a RoR portofilio project.</p>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to <i>Simply Do</i></h1>
  <% if not logged_in? %>
    <h1>
      <small>Sign in</small>
    </h1>
  <br>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span> Remember me</span>
      <% end %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
  <% end %>
</div>
</div>
<br>
<p>New user? <%= link_to "Sign up now!", signup_path %></p>

<% end %>
</div>